---
title: "Amazon Product Analysis"
authors: 'Nathan Thomas, Benjamin Tuohey, Ivan Voinov'
output: html_notebook
---

# Importing/Cleaning Data
```{r}
Amazon_Products <- read.csv('Amazon_Product.csv')
head(Amazon_Products)
```

### Cleaning Data
```{r}
colnames(Amazon_Products)
```

### Removes 800+ empty columns - filters down to 14
```{r}
Amazon_Products_Cleaned <- subset(Amazon_Products, select = c(uniq_id, product_name, manufacturer, price, number_available_in_stock, number_of_reviews, number_of_answered_questions, average_review_rating, amazon_category_and_sub_category, description, product_information, product_description, items_customers_buy_after_viewing_this_item, customer_questions_and_answers))
```

```{r}
head(Amazon_Products_Cleaned)
```

### Writes Dataset as CSV for export
```{r}
write.csv(Amazon_Products_Cleaned,'Amazon_Products_Cleaned.csv')
```

### Convert Price from Pound to Dollar

```{r}
#Current exchange rate is 1 Pound : 1.30 USD as of 4/9/2022
summary(Amazon_Products_Cleaned)
```

### Price is currently character, need to remove the pound symbol and convert to float type
```{r}
Amazon_Products_Cleaned$price<-gsub("£","",as.character(Amazon_Products_Cleaned$price))
```

```{r}
View(Amazon_Products_Cleaned)
```

```{r}
library(tidyverse)
Amazon_Products_Cleaned <- Amazon_Products_Cleaned %>%
  mutate(price = as.numeric(price), 
         number_of_reviews = as.numeric(number_of_reviews),
         number_of_answered_questions = as.numeric(number_of_answered_questions))
Amazon_Products_Cleaned$price <- Amazon_Products_Cleaned$price*1.30
```

```{r}
head(Amazon_Products_Cleaned)
```

# Initial Statistics/Plots
## Statistics

```{r}
Amazon_Products_Cleaned %>%
  summarise(num_cases = n(), 
            mean_price = mean(price, na.rm=T),
            med_price = median(price, na.rm=T),
            mean_reviews = mean(number_of_reviews, na.rm=T),
            )
```


## Plots
###Boxplot
```{r}
Amazon_Products_Cleaned %>%
  ggplot(aes(y=price)) +
  geom_boxplot()
```
There are a lot of outliers, let's adjust the scale.

```{r}
Amazon_Products_Cleaned %>%
  ggplot(aes(y=price)) +
  geom_boxplot() +
  ylim(0,25)
```
